sudo: required
dist: trusty
language: bash
addons:
  apt:
    packages:
      fakeroot
before_install:
  - wget http://dev2day.de/skeleton.tgz
  - wget http://downloads.plex.tv/plex-media-server/1.1.0.2611-ba905d2/PlexMediaServer-1.1.0.2611-ba905d2-arm7.spk
install:
  - tar -xzf skeleton.tgz
  - tar -xvf PlexMediaServer-1.1.0.2611-ba905d2-arm7.spk
  - tar -xvf package.tgz -C skeleton/usr/lib/plexmediaserver
  - rm -r skeleton/usr/lib/plexmediaserver/dsm_config
  - find skeleton/usr/lib/plexmediaserver -iname "*.so" -exec chmod 644 {} \;
  - find skeleton/usr/lib/plexmediaserver -iname "*.so.*" -exec chmod 644 {} \;
script:
  fakeroot dpkg-deb --build skeleton ./
